config/routes.rb
NinjaProject::Application.routes.draw do

  root :to => "home#index"

  get "home/index", :as => :home

  get "home/admin", :as => :admin

  get "search/index", :as => :search

  post "search/results", :as => :search_results

  resources :assessment_recipes

  resources :assessments

  resources :tags

  resources :dishes

  resources :recipes

  resources :ingredients

  resources :ingredient_categories

  resources :needed_ingredients

  resources :recipe_tags

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def admin
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.html.erb
<%= mininav(["Admin"]) %>
<br/>
<table border="1">
  <tr>
    <td>Zutat Kategorie</td>
    <td>Zutat</td>
    <td>Gericht</td>
    <td>Rezept</td>
  </tr>
  <tr>
    <td><%= link_to "New", new_ingredient_category_path %></td>
    <td><%= link_to "New", new_ingredient_path %></td>
    <td><%= link_to "New", new_dish_path %></td>
    <td><%= link_to "New", new_recipe_path %></td>
  </tr>
  <tr>
    <td><%= link_to "Edit", edit_ingredient_category_path(IngredientCategory.last) %></td>
    <td><%= link_to "Edit", edit_ingredient_path(Ingredient.last) %></td>
    <td><%= link_to "Edit", edit_dish_path(Dish.last) %></td>
    <td><%= link_to "Edit", edit_recipe_path(Recipe.last) %></td>
  </tr>
  <tr>
    <td><%= link_to 'Delete', IngredientCategory.last, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= link_to "Delete", Ingredient.last, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= link_to "Delete", Dish.last, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= link_to "Delete", Recipe.last, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
</table>

app/views/home/index.html.erb
<%= mininav(["Home"])  %>
<br/>
Hier gibt es später die neusten der neusten Infos.