config/routes.rb
NinjaProject::Application.routes.draw do

  root :to => "home#index"

  get "home/index", :as => :home

  get "home/admin", :as => :admin

  get "search/index", :as => :search

  post "search/results", :as => :search_results

  resources :assessment_recipes

  resources :assessments

  resources :tags

  resources :dishes

  resources :recipes

  resources :ingredients

  resources :ingredient_categories

  resources :needed_ingredients

  resources :recipe_tags

end

app/models/ingredient_category.rb
class IngredientCategory < ActiveRecord::Base
#  attr_protected :id, :created_at, :updated_At
  belongs_to :parent, :foreign_key => "parent_id", :class_name => "IngredientCategory"
  has_one :ingredient
  has_many :ingredient_categories
end

app/controllers/ingredient_categories_controller.rb
class IngredientCategoriesController < ApplicationController
  # GET /ingredient_categories
  # GET /ingredient_categories.json
  def index
    @ingredient_categories = IngredientCategory.where("level=0")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredient_categories }
    end
  end

  # GET /ingredient_categories/1
  # GET /ingredient_categories/1.json
  def show
    @ingredient_categories = IngredientCategory.where("parent_id=?",params[:id])
    if @ingredient_categories.empty?
      @ingredients = Ingredient.where("ingredient_category_id=?",params[:id])
      if @ingredients.empty?
        @ingredient_category = IngredientCategory.find(params[:id])
      end
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient_category }
    end
  end

  # GET /ingredient_categories/new
  # GET /ingredient_categories/new.json
  def new
    @ingredient_category = IngredientCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient_category }
    end
  end

  # GET /ingredient_categories/1/edit
  def edit
    @ingredient_category = IngredientCategory.find(params[:id])
  end

  # POST /ingredient_categories
  # POST /ingredient_categories.json
  def create
    @ingredient_category = IngredientCategory.new(params[:ingredient_category])
    unless @ingredient_category.parent.nil?
      @ingredient_category.level = @ingredient_category.parent.level + 1
    else
      @ingredient_category.level = 0
    end
    respond_to do |format|
      if @ingredient_category.save
        format.html { redirect_to @ingredient_category, notice: 'Ingredient category was successfully created.' }
        format.json { render json: @ingredient_category, status: :created, location: @ingredient_category }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredient_categories/1
  # PUT /ingredient_categories/1.json
  def update
    @ingredient_category = IngredientCategory.find(params[:id])

    respond_to do |format|
      if @ingredient_category.update_attributes(params[:ingredient_category])
        format.html { redirect_to @ingredient_category, notice: 'Ingredient category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredient_categories/1
  # DELETE /ingredient_categories/1.json
  def destroy
    @ingredient_category = IngredientCategory.find(params[:id])
    @ingredient_category.destroy

    respond_to do |format|
      format.html { redirect_to ingredient_categories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/ingredient_categories_helper.rb
module IngredientCategoriesHelper
  def getIngredientCategory ingredient
    ic = ingredient.ingredient_category

    hierarchy = [ic.name]

    while ic.parent
      hierarchy.insert(0, (link_to ic.parent.name, ingredient_category_path(ic.parent)))
      ic = ic.parent
    end

    hierarchy
  end

  def getCategoryParent category

    hierarchy = [category.name]
    if category.parent
      cp = category.parent

      hierarchy = [(link_to cp.name, ingredient_category_path(cp.parent))]

      while cp.parent
        hierarchy.insert(0, (link_to cp.parent.name, ingredient_category_path(cp.parent)))
        cp = cp.parent
      end
    end
    hierarchy
  end
end

app/views/ingredient_categories/_form.html.erb
<%= form_for(@ingredient_category) do |f| %>
  <% if @ingredient_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient_category.errors.count, "error") %> prohibited this ingredient_category from being saved:</h2>

      <ul>
      <% @ingredient_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Oberkategorie:" %><br />
    <%= f.collection_select(:parent_id, IngredientCategory.all, :id, :name, {:include_blank => true} ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredient_categories/edit.html.erb
<%= mininav(["Zutaten", (link_to "Kategorien", ingredient_categories_path)] + getCategoryParent(@ingredient_category) + [(link_to @ingredient_category.name, ingredient_category_path(@ingredient_category)), "Bearbeiten"]) %>

<br />

<%= render 'form' %>

app/views/ingredient_categories/index.html.erb
<%= mininav(["Zutaten", "Kategorien"]) %>

<br/>

<% @ingredient_categories.each do |ingredient_category| %>

<%= link_to ingredient_category.name, ingredient_category_path(ingredient_category)  %>

<% end %>

<br />
<br />

<%= link_to 'New Ingredient category', new_ingredient_category_path %>

app/views/ingredient_categories/new.html.erb
<%= mininav(["Zutaten", (link_to "Kategorien", ingredient_categories_path), "Neu"]) %>

<br />

<%= render 'form' %>

app/views/ingredient_categories/show.html.erb
<% unless @ingredient_categories.empty?  %>
    <%= mininav(["Zutaten",(link_to "Kategorien", ingredient_categories_path)] + getCategoryParent(@ingredient_categories.first)) %>
    <% @ingredient_categories.each do |ingredient_category| %>
        <%= link_to ingredient_category.name, ingredient_category_path(ingredient_category)  %>
    <% end %>
<% else %>
    <% if @ingredients.empty? %>
        <%= mininav(["Zutaten", (link_to "Kategorien", ingredient_categories_path)] + getCategoryParent(@ingredient_category) + [@ingredient_category.name]) %>
        <%= link_to "Neue Zutat", new_ingredient_path %>
    <% else %>
        <%= mininav(["Zutaten",(link_to "Kategorien", ingredient_categories_path)] + getIngredientCategory(@ingredients.first)) %>
        <% @ingredients.each do |ingredient| %>
            <%= link_to ingredient.name, ingredient_path(ingredient)  %>
        <% end %>
        <br />
        <br />
        <%= link_to "Neue Zutat", new_ingredient_path %>
    <% end %>
<% end %>
<br />