config/routes.rb
NinjaProject::Application.routes.draw do

  root :to => "home#index"

  get "home/index", :as => :home

  get "home/admin", :as => :admin

  get "search/index", :as => :search

  post "search/results", :as => :search_results

  resources :assessment_recipes

  resources :assessments

  resources :tags

  resources :dishes

  resources :recipes

  resources :ingredients

  resources :ingredient_categories

  resources :needed_ingredients

  resources :recipe_tags

end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
  validates :rating, :presence => true

  belongs_to :recipe
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  validates :name, :presence => true
  attr_protected :id, :created_at, :updated_at
  has_many :recipes
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates :name, :presence => true
  validates :ingredient_category_id, :presence => true

  attr_protected :id, :created_at, :updated_at
  belongs_to :ingredient_category
  has_many :recipes, :through => :needed_ingredients
end

app/models/ingredient_category.rb
class IngredientCategory < ActiveRecord::Base
#  attr_protected :id, :created_at, :updated_At
  belongs_to :parent, :foreign_key => "parent_id", :class_name => "IngredientCategory"
  has_one :ingredient
  has_many :ingredient_categories
end

app/models/needed_ingredient.rb
class NeededIngredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :dish_id, :presence => true
  validates :making, :presence => true

  attr_accessible :name, :making
  belongs_to :dish
  belongs_to :author
  has_many :assessments
  has_many :needed_ingredients
  has_many :ingredients, :through => :needed_ingredients
  has_many :recipe_tags
  has_many :tags, :through => :recipe_tags
end

app/models/recipe_tag.rb
class RecipeTag < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :recipes, :through => :needed_ingredients
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dishes }
    end
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
    @recipes = Recipe.where("dish_id=?",params[:id])
    @dish = Dish.find(params[:id])
      respond_to do |format|
        format.html #  recipe_in_categorie.html.erb
        format.json { render json: @recipes }
    end
  end

  # GET /dishes/new
  # GET /dishes/new.json
  def new
    @dish = Dish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/1/edit
  def edit
    @dish = Dish.find(params[:id])
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(params[:dish])

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render json: @dish, status: :created, location: @dish }
      else
        format.html { render action: "new" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dishes/1
  # PUT /dishes/1.json
  def update
    @dish = Dish.find(params[:id])

    respond_to do |format|
      if @dish.update_attributes(params[:dish])
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to home_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def admin
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def mininav text
    html = "<div class='mininav'>"

    text.each do |element|
      html += element
      unless text.last == element
        html += " > "
      end
    end
    html += "</div>"
    html.html_safe
  end
end

app/helpers/assessment_recipes_helper.rb
module AssessmentRecipesHelper
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
  def getCategory ingredient
    ic = ingredient.ingredient_category

    hierarchy = [(link_to ic.name, ingredient_category_path(ic))]

    while ic.parent
      hierarchy.insert(0, (link_to ic.parent.name, ingredient_category_path(ic.parent)))
      ic = ic.parent
    end

    hierarchy
  end
end

app/helpers/recipe_tags_helper.rb
module RecipeTagsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def unit_to_i unit
      units = {"" => 0, "Stueck" => 1, "kg" => 2, "gr" => 3, "Liter" => 4, "ml" => 5}
      units[unit].to_i
    end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/assessment_recipes/_form.html.erb
<%= form_for(@assessment_recipe) do |f| %>
  <% if @assessment_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assessment_recipe.errors.count, "error") %> prohibited this assessment_recipe from being saved:</h2>

      <ul>
      <% @assessment_recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe %><br />
    <%= f.text_field :recipe %>
  </div>
  <div class="field">
    <%= f.label :assessment %><br />
    <%= f.text_field :assessment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assessment_recipes/edit.html.erb
<h1>Editing assessment_recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @assessment_recipe %> |
<%= link_to 'Back', assessment_recipes_path %>

app/views/assessment_recipes/index.html.erb
<h1>Listing assessment_recipes</h1>

<table>
  <tr>
    <th>Recipe</th>
    <th>Assessment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assessment_recipes.each do |assessment_recipe| %>
  <tr>
    <td><%= assessment_recipe.recipe %></td>
    <td><%= assessment_recipe.assessment %></td>
    <td><%= link_to 'Show', assessment_recipe %></td>
    <td><%= link_to 'Edit', edit_assessment_recipe_path(assessment_recipe) %></td>
    <td><%= link_to 'Destroy', assessment_recipe, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assessment recipe', new_assessment_recipe_path %>

app/views/assessment_recipes/new.html.erb
<h1>New assessment_recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', assessment_recipes_path %>

app/views/assessment_recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Recipe:</b>
  <%= @assessment_recipe.recipe %>
</p>

<p>
  <b>Assessment:</b>
  <%= @assessment_recipe.assessment %>
</p>


<%= link_to 'Edit', edit_assessment_recipe_path(@assessment_recipe) %> |
<%= link_to 'Back', assessment_recipes_path %>